server:
  port: 10005

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: update
#      ddl-auto: validate
    properties:
      hibernate:
        use_sql_comments: true
        database-platform: org.hibernate.dialect.Oracle10gDialect