insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Andalax', 14800, '2022-07-07', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Alphazap', 18700, '2021-03-06', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Opela', 23600, '2020-06-24', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Sub-Ex', 21400, '2022-09-02', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Transcof', 38000, '2022-05-26', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Veribet', 43300, '2023-08-19', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Greenlam', 44900, '2021-05-01', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Zaam-Dox', 37400, '2021-11-28', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Fintone', 29400, '2021-12-16', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Flexidy', 40800, '2023-08-01', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Job', 34900, '2022-04-09', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Otcom', 12100, '2022-10-18', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Andalax', 40600, '2022-09-06', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Asoka', 33300, '2022-08-28', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Trippledex', 42300, '2022-06-19', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Zamit', 44100, '2023-01-22', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Zontrax', 35400, '2021-05-19', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Rank', 17000, '2023-09-05', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Tin', 23300, '2021-03-13', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Aerified', 18200, '2021-05-07', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Vagram', 28200, '2022-07-14', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Keylex', 36200, '2023-05-30', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Bamity', 19900, '2023-02-14', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Job', 10500, '2021-05-19', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Aerified', 35300, '2021-03-29', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Alphazap', 32800, '2020-11-08', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Temp', 30300, '2023-02-08', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Domainer', 35400, '2022-07-28', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Viva', 11000, '2023-06-29', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Ronstring', 30400, '2022-07-28', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Fintone', 17300, '2021-04-29', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Tres-Zap', 43800, '2023-07-04', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Subin', 19700, '2022-10-25', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Lotstring', 43400, '2021-05-29', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Gembucket', 31700, '2022-02-07', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Flowdesk', 44100, '2022-08-17', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Regrant', 29900, '2023-05-12', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Aerified', 20100, '2022-03-16', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Tresom', 23100, '2021-08-28', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Viva', 40100, '2021-11-08', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Konklux', 30200, '2020-09-30', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Opela', 20700, '2021-09-14', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Wrapsafe', 12500, '2021-01-27', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Tin', 42000, '2022-03-11', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Viva', 11700, '2020-09-20', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Bamity', 34200, '2023-08-17', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Pannier', 29100, '2022-07-21', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Fix San', 34900, '2021-04-25', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Daltfresh', 23300, '2023-07-06', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Job', 33400, '2022-07-26', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Ronstring', 27600, '2023-06-27', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Home Ing', 31800, '2020-06-19', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Y-find', 17800, '2023-06-30', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Zoolab', 10600, '2022-03-29', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Regrant', 15400, '2021-07-07', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Subin', 31300, '2022-04-22', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Lotlux', 43700, '2021-01-10', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Namfix', 37700, '2023-04-12', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Alpha', 25200, '2021-05-26', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Matsoft', 39000, '2020-08-29', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Bitwolf', 28500, '2023-05-08', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Job', 21100, '2023-07-18', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Alpha', 44700, '2023-05-23', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Aerified', 34900, '2023-07-03', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Zaam-Dox', 29800, '2021-08-02', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Y-Solowarm', 33800, '2023-03-10', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Fixflex', 43200, '2023-01-13', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Job', 43800, '2021-04-12', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Tres-Zap', 12100, '2023-03-10', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Cookley', 38700, '2023-07-02', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Y-Solowarm', 38400, '2020-07-16', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Tresom', 22400, '2021-04-09', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Otcom', 11600, '2021-12-11', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Stringtough', 23300, '2023-09-11', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Holdlamis', 12600, '2023-08-14', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Vagram', 14500, '2023-01-26', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Zoolab', 26100, '2022-03-08', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Andalax', 28500, '2021-03-03', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Stringtough', 13300, '2020-09-26', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Job', 21300, '2021-01-15', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Fintone', 35500, '2021-06-27', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Flexidy', 13400, '2023-10-09', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Domainer', 28200, '2021-02-09', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Opela', 22400, '2021-04-20', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Aerified', 12400, '2020-12-05', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Voyatouch', 12600, '2022-06-02', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Vagram', 17900, '2020-09-14', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Cookley', 22000, '2021-12-02', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Quo Lux', 15800, '2020-12-08', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Sub-Ex', 27200, '2022-10-30', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Job', 11300, '2022-01-15', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Cookley', 12500, '2022-12-07', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Voyatouch', 39900, '2022-04-27', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'SCIENCE', 'Namfix', 22700, '2021-08-02', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Span', 39900, '2021-02-05', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Tresom', 33200, '2023-05-31', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'It', 11200, '2020-07-22', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'NOVEL', 'Lotstring', 25300, '2021-09-05', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'IT', 'Rank', 35300, '2023-01-19', 'false');
insert into JPA_BOOK (book_id, category, name, price, release_date, deleted) values (SEQ_BOOK.nextval, 'HISTORY', 'Konklux', 13100, '2021-06-05', 'false');


insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Laetitia Venus', '882-735-1004', '1992-05-20', '강서구', 'Suite 71', '7910', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Benji Swadlen', '650-797-5940', '1996-10-16', '강동구', 'PO Box 62848', '6', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Archibold Pashbee', '436-478-9997', '1984-03-06', '강남구', 'PO Box 91117', '1608', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Gonzales Jiggle', '460-777-0385', '1991-12-16', '강북구', 'Apt 53', '70665', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Whit Itzkin', '359-875-4063', '1989-07-02', '강서구', 'Suite 53', '816', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Rebe Pococke', '919-949-6790', '2008-04-14', '강서구', 'Suite 91', '33', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Towny Senogles', '769-631-3692', '2008-09-25', '강남구', 'Apt 773', '4320', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Robbin Millgate', '949-465-2567', '2009-07-27', '강동구', '5th Floor', '9718', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Zacherie Van Salzberger', '830-384-7347', '1993-07-27', '강북구', '16th Floor', '736', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Hedvig Bugge', '588-676-3957', '2003-08-04', '강서구', 'PO Box 60311', '86816', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Lorne Pairpoint', '310-280-6826', '1981-09-14', '강북구', 'Suite 92', '68932', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Virginie Houseman', '829-109-5935', '1987-01-09', '강남구', 'Suite 37', '134', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Chadd Spiaggia', '163-241-1158', '2000-12-27', '강북구', 'Suite 46', '85', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Kaile Joules', '351-842-8697', '2010-11-04', '강북구', 'Apt 1936', '06084', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Kiah Petrollo', '259-949-7436', '1986-12-28', '강남구', 'PO Box 98644', '79', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Menard Jeannin', '361-771-8588', '2000-12-09', '강동구', 'Room 43', '55280', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Darin Drakeford', '774-441-8414', '2010-02-24', '강서구', 'Room 23', '093', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Chlo Hebblethwaite', '432-887-3511', '2005-04-05', '강동구', 'Room 1439', '166', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Bruno Print', '126-724-7259', '2008-02-22', '강동구', 'PO Box 49684', '2', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Juan McMorland', '915-629-3381', '2003-06-12', '강동구', 'Room 1724', '6821', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Florenza Flucker', '459-522-1272', '2002-07-16', '강남구', 'Apt 1089', '0', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Tildy McKennan', '866-997-6276', '1996-06-27', '강북구', 'Apt 1906', '53797', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Nathanael Cray', '351-208-9418', '1990-02-05', '강북구', 'PO Box 34950', '326', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Derby Elsay', '928-413-8247', '2003-11-29', '강북구', 'Room 1450', '091', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'North Richardeau', '203-517-4985', '2007-04-05', '강남구', 'Suite 11', '54957', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Louisette Crew', '504-705-7489', '2007-06-04', '강동구', '4th Floor', '1765', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Nevsa Brigden', '497-575-8207', '1998-03-02', '강서구', '4th Floor', '5', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Addy Fallanche', '955-136-1840', '1986-07-25', '강남구', '10th Floor', '8', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Kellen Pyper', '769-164-4182', '1998-04-30', '강동구', 'Room 696', '48', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Tammara Huntingdon', '665-798-6506', '1989-01-15', '강남구', 'Suite 63', '78', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Haywood Garces', '612-638-2646', '1998-11-15', '강서구', 'Suite 24', '9', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Rosanna Scuse', '982-578-3131', '1990-06-29', '강동구', 'PO Box 63899', '433', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Kit Bunkle', '610-860-1797', '1994-09-13', '강서구', 'Suite 98', '2795', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Essy Fryett', '999-262-1654', '2007-09-07', '강북구', 'Apt 527', '0066', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Cate Vardie', '671-601-4160', '2004-07-22', '강북구', 'Apt 99', '750', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Roseline Kidde', '939-169-9245', '1981-07-17', '강동구', 'Suite 18', '63', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Jefferson Hawler', '779-919-4627', '2000-11-21', '강서구', 'Suite 7', '16949', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Valida Ubach', '860-556-7445', '1991-03-07', '강서구', 'PO Box 76978', '43738', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Nixie Kilban', '739-207-6961', '1993-04-24', '강동구', '6th Floor', '79', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Cherilynn Gallone', '923-587-1404', '1996-11-10', '강동구', 'PO Box 55514', '2299', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Gertrudis Spataro', '815-824-2984', '1983-12-08', '강북구', 'PO Box 31497', '593', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Brady Pellissier', '571-692-7078', '2003-06-10', '강동구', 'PO Box 92186', '0', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Katuscha Tutt', '313-897-9073', '2000-04-08', '강남구', 'PO Box 20374', '83', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Tiena McKearnen', '524-975-5182', '2007-09-18', '강서구', 'Apt 1562', '05888', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Joletta MacGowan', '706-653-6347', '1991-11-02', '강동구', '16th Floor', '89596', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Aurelia Emm', '152-344-2639', '1997-02-18', '강서구', 'Room 1909', '51270', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Thatch Cabble', '637-436-9892', '1990-02-04', '강서구', 'Suite 18', '4743', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Gretta Absalom', '530-395-7661', '1993-08-23', '강서구', 'Suite 91', '91', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Luce Kienl', '530-352-1302', '2004-02-27', '강북구', 'Room 681', '2678', 'false');
insert into JPA_USER (user_id, name, phone, birth, address, address_detail, zipcode, deleted) values (SEQ_USER.nextval, 'Camila Matschke', '644-571-9507', '1983-05-13', '강남구', 'PO Box 43169', '1', 'false');

insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (1, 57, 49, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (2, 12, 6, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (3, 83, 15, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (4, 29, 15, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (5, 66, 38, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (6, 41, 16, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (7, 95, 2, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (8, 7, 42, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (9, 34, 24, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (10, 71, 24, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (11, 18, 46, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (12, 92, 47, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (13, 47, 23, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (14, 76, 25, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (15, 23, 4, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (16, 88, 4, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (17, 53, 50, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (18, 38, 22, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (19, 81, 8, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (20, 16, 5, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (21, 61, 21, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (22, 99, 9, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (23, 44, 32, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (24, 69, 34, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (25, 26, 47, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (26, 91, 35, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (27, 56, 22, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (28, 31, 47, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (29, 74, 1, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (30, 9, 37, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (31, 64, 49, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (32, 39, 47, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (33, 86, 21, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (34, 51, 46, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (35, 36, 49, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (36, 79, 44, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (37, 14, 26, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (38, 77, 37, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (39, 21, 35, 'false');
insert into JPA_CHECK_OUT (check_out_id, book_id, user_id, deleted) values (40, 96, 31, 'false');
commit;